// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AbstractList: typeof import('./../components/lists/AbstractList.vue')['default']
    AddEventMember: typeof import('./../components/forms/AddEventMember.vue')['default']
    Address: typeof import('./../components/Address.vue')['default']
    Button: typeof import('primevue/button')['default']
    ChangeGenderForm: typeof import('./../components/forms/ChangeGenderForm.vue')['default']
    ChangePasswordForm: typeof import('./../components/forms/ChangePasswordForm.vue')['default']
    ChangeRoleForm: typeof import('./../components/forms/ChangeRoleForm.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EventEditForm: typeof import('./../components/forms/EventEditForm.vue')['default']
    EventList: typeof import('./../components/lists/EventList.vue')['default']
    EventNameList: typeof import('./../components/lists/EventNameList.vue')['default']
    EventTable: typeof import('./../components/tables/EventTable.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./../components/forms/LoginForm.vue')['default']
    Logout: typeof import('./../components/Logout.vue')['default']
    Members: typeof import('./../components/Members.vue')['default']
    Password: typeof import('primevue/password')['default']
    PasswordSecure: typeof import('./../components/forms/components/PasswordSecure.vue')['default']
    RegisterForm: typeof import('./../components/forms/RegisterForm.vue')['default']
    ResetPasswordForm: typeof import('./../components/forms/ResetPasswordForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamCreateForm: typeof import('./../components/forms/TeamCreateForm.vue')['default']
    Teams: typeof import('./../components/Teams.vue')['default']
    UserCreateForm: typeof import('./../components/forms/UserCreateForm.vue')['default']
    UserList: typeof import('./../components/lists/UserList.vue')['default']
    UserTable: typeof import('./../components/tables/UserTable.vue')['default']
  }
}
