// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AbstractList: typeof import('./../components/lists/AbstractList.vue')['default']
    Accordion: typeof import('primevue/accordion')['default']
    AccordionTab: typeof import('primevue/accordiontab')['default']
    AddMemberForm: typeof import('./../components/forms/members/AddMemberForm.vue')['default']
    Address: typeof import('./../components/Address.vue')['default']
    Button: typeof import('primevue/button')['default']
    ChangeGenderForm: typeof import('./../components/forms/users/ChangeGenderForm.vue')['default']
    ChangePasswordForm: typeof import('./../components/forms/users/ChangePasswordForm.vue')['default']
    ChangeRoleForm: typeof import('./../components/forms/users/ChangeRoleForm.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    EventAddMemberForm: typeof import('./../components/forms/members/EventAddMemberForm.vue')['default']
    EventEditForm: typeof import('./../components/forms/EventEditForm.vue')['default']
    EventList: typeof import('./../components/lists/EventList.vue')['default']
    EventMembers: typeof import('./../components/members/EventMembers.vue')['default']
    EventNameList: typeof import('./../components/lists/EventNameList.vue')['default']
    EventTable: typeof import('./../components/tables/EventTable.vue')['default']
    EventTableBasic: typeof import('./../components/tables/EventTableBasic.vue')['default']
    EventTests: typeof import('./../components/EventTests.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    JoinEventForm: typeof import('./../components/forms/JoinEventForm.vue')['default']
    LoginForm: typeof import('./../components/forms/users/LoginForm.vue')['default']
    Logout: typeof import('./../components/Logout.vue')['default']
    Members: typeof import('./../components/members/Members.vue')['default']
    Password: typeof import('primevue/password')['default']
    PasswordSecure: typeof import('./../components/forms/components/PasswordSecure.vue')['default']
    RegisterForm: typeof import('./../components/forms/users/RegisterForm.vue')['default']
    ResetPasswordForm: typeof import('./../components/forms/ResetPasswordForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskCreateForm: typeof import('./../components/forms/TaskCreateForm.vue')['default']
    Tasks: typeof import('./../components/Tasks.vue')['default']
    TeamAddMemberForm: typeof import('./../components/forms/members/TeamAddMemberForm.vue')['default']
    TeamCreateForm: typeof import('./../components/forms/TeamCreateForm.vue')['default']
    TeamEditForm: typeof import('./../components/forms/TeamEditForm.vue')['default']
    TeamMembers: typeof import('./../components/members/TeamMembers.vue')['default']
    Teams: typeof import('./../components/Teams.vue')['default']
    Tests: typeof import('./../components/Tests.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    UserCreateForm: typeof import('./../components/forms/users/UserCreateForm.vue')['default']
    UserList: typeof import('./../components/lists/UserList.vue')['default']
    UserTable: typeof import('./../components/tables/UserTable.vue')['default']
  }
}
