// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Address: typeof import('./../components/Address.vue')['default']
    Button: typeof import('primevue/button')['default']
    Divider: typeof import('primevue/divider')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    Header: typeof import('./../components/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LoginForm: typeof import('./../components/forms/LoginForm.vue')['default']
    Password: typeof import('primevue/password')['default']
    PasswordSecure: typeof import('./../components/forms/components/PasswordSecure.vue')['default']
    RegisterForm: typeof import('./../components/forms/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectButton: typeof import('primevue/selectbutton')['default']
  }
}
